language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - composer update

script: phpunit --coverage-text tests/
