forgot:
  route: /forgot
  action: forgot

mailing_test_email:
  route: /mailing/test
  action: testEmail

mailing_save_incoming_account:
  route: '/mailing/:project_key/incoming_account/*'
  action: saveIncomingAccount

mailing_check_account:
  route: /mailing/incoming_account/:account_id/check
  action: checkIncomingAccount

mailing_delete_account:
  route: /mailing/incoming_account/:account_id/delete
  action: deleteIncomingAccount

configure_mailing_settings:
  route: /configure/project/:project_id/mailing
  action: configureProjectSettings
  parameters:
    config_module: core
    section: 15
